### ISSUE TITLE
Após  a última atualização do woocommerce deu erro 

### ISSUE THREAD

**Issue by kristyan10** [claudiosanches/woocommerce-extra-checkout-fields-for-brazil#117]
Após a última atualização do woocommerce deu erro na disposição dos campos do checkout, com o uso do plugin woocommerce-extra-checkout-fields-for-brazil

**Comment by kristyan10** [comment]
Após  a última atualização do woocommerce deu erro na disposição dos campos do checkout, com o uso do plugin woocommerce-extra-checkout-fields-for-brazil

**Comment by nilsonalvarenga** [comment]
Pra mim tb, estou com erro nesta tela

**Comment by iztalo** [comment]
Mesma coisa aqui. Os campos ficaram desalinhados, a máscara do telefone e da data de nascimento pararam de funcionar e a label do complemento desapareceu.

**Comment by nilsonalvarenga** [comment]
Eu consegui resolver, foi voltando as versões anteriores

**Comment by CasperBraske** [comment]
Uma solução temporária aqui foi adicionar margin-top aos campos com CSS:

```CSS
#billing_address_2_field, 
#shipping_address_2_field {
    margin-top: 25px; /* ou o quanto bastar */
}
```
